Forgot to include file in last commit
Co-authored-by: Caleb Soong <121209059+caleb-soong@users.noreply.github.com>

diff --git a/src/templates/buildImage.yml b/src/templates/buildImage.yml
--- a/src/templates/buildImage.yml
+++ b/src/templates/buildImage.yml
@@ -9,25 +9,24 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
 
-      CONFIG_FILE=".vizier/config.json"
-      if [ ! -f "$CONFIG_FILE" ]; then
-      echo "$CONFIG_FILE not found. Run vizier init to generate it." >&2
-      exit 1
-      fi
-      PROJECT_ID=$(jq -r '.projectId // empty' "$CONFIG_FILE")
-      if [ -z "$=PROJECT_ID" ]; then
-      echo "projectId missing from $CONFIG_FILE" >&2
-      cat "$CONFIG_FILE"
-      exit 1
-      fi
-      echo "PROJECT_ID=$PROJECT_ID" >> "$GITHUB_ENV"
-    # env:
-    #   ECR_REPOSITORY: ${{ PROJECT_ID }}
-    #   IMAGE_TAG: ${{ github.sha }}
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
+      - name: Get project id from config
+        run: |
+          CONFIG_FILE=".vizier/config.json"
+          if [ ! -f "$CONFIG_FILE" ]; then
+            echo "$CONFIG_FILE not found. Run vizier init to generate it." >&2
+            exit 1
+          fi
+            PROJECT_ID=$(jq -r '.projectId // empty' "$CONFIG_FILE")
+            if [ -z "$PROJECT_ID" ]; then
+            echo "projectId missing from $CONFIG_FILE" >&2
+            cat "$CONFIG_FILE"
+            exit 1
+          fi
+          echo "PROJECT_ID=$PROJECT_ID" >> "$GITHUB_ENV"
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v3
